apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      standalone:
        enabled: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "gcs" {
            bucket = "vault-storage-prj-d-kon-secret-24f1"
          }

          seal "gcpckms" {
            project     = "prj-d-kon-secret-24f1"
            region      = "global"
            key_ring    = "keyring-kon"
            crypto_key  = "crypto-key-vault"
          }
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: sa-vault@prj-d-kon-secret-24f1.iam.gserviceaccount.com
