apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kon-hasura-metadata
  namespace: main
spec:
  interval: 5m
  path: "./overlay/development/kon/hasura-metadata"
  dependsOn:
    - name: istio-system
      namespace: flux-system
    - name: vault
      namespace: flux-system
    - name: kon-zoru
  prune: true
  sourceRef:
    kind: GitRepository
    name: main-branch
    namespace: flux-system
  validation: client
