apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vault-secrets-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./overlay/development/vault-secrets-operator/"
  dependsOn:
    - name: vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
