apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./overlay/development/istio/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 5m
  path: "./overlay/development/istio/system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - kind: Deployment
      name: istiod
      namespace: istio-system
  timeout: 2m
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  path: "./overlay/development/istio/grafana"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jaeger
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  path: "./overlay/development/istio/jaeger"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kiali
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  path: "./overlay/development/istio/kiali"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  path: "./overlay/development/istio/prometheus"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
