apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - ../../../../../base/branching/app
patchesStrategicMerge:
  - alpi_sync.yaml
  - nami_sync.yaml
  - hasura_sync.yaml
  - zoru_sync.yaml
  - hasura-metadata_sync.yaml
  - common_sync.yaml
