apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hasura
  namespace: main
spec:
  interval: 2m
  chart:
    spec:
      chart: hasura
      version: 0.0.0
      sourceRef:
        kind: HelmRepository
        name: prj-sh-kon-helm-c2a1
        namespace: main
