apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator
spec:
  interval: 2m
  chart:
    spec:
      chart: vault-secrets-operator
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-operator
        namespace: flux-system
  values:
    vault:
      authMethod: kubernetes
      address: "http://vault.vault.svc.cluster.local"
