apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vault-secrets-operator
  namespace: flux-system
spec:
  interval: 2m
  url: https://ricoberger.github.io/helm-charts
