apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-monitoring-preparation
  namespace: flux-system
spec:
  interval: 5m
  path: "./overlay/development/flux-monitoring/"
  dependsOn:
    - name: istio-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
