apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
    tag: v0.5.8
  url: https://github.com/fluxcd/flux2