apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: flux-system
spec:
  hosts:
    - flux.system.dev.dmoiseenko.me
  gateways:
    - istio-system/iap-ingress-gateway
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 3000
