apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pgo
  namespace: flux-system
spec:
  interval: 5m
  path: "./overlay/development/pgo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
