apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: istio-system
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
