apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure/ingress
patchesStrategicMerge:
  - ingress.yaml
  - iap_backend_config.yaml
  - default_backend_config.yaml
