apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nami
  namespace: main
spec:
  interval: 2m
  chart:
    spec:
      chart: nami
      version: 0.0.0
      sourceRef:
        kind: HelmRepository
        name: prj-sh-kon-helm-c2a1
        namespace: main
  values:
    image:
      repository: "us-east1-docker.pkg.dev/prj-sh-kon-registry-4846/kon/nami"