apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: 1.1.0
  values:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: sa-main@prj-d-kon-dns-96ae.iam.gserviceaccount.com
