apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hasura-metadata
  namespace: main
spec:
  chart:
    spec:
      version: 0.0.568539394+1982a42952c176fd5660ccf353c47fe959b9bbd9
