apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../../base/infrastructure/external-dns
patchesStrategicMerge:
  - service_account.yaml
  - deployment.yaml
